version: "3.9"
services:
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web

  redis:
    image: redis:alpine
    platform: linux/arm64
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    platform: linux/arm64
    container_name: keycloak
    depends_on:
      - db
    ports:
      - "8080:8080"
    
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres:5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
    command: "-Dkeycloak.profile.feature.upload_scripts=enabled"
    
    
   
   
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak,e-commerce
    volumes:
      - ./db-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

        
        
  api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    container_name: ecommerceapi
    build:
      context: .
      dockerfile: E-Commerce.API/Dockerfile
    ports:
      - "8023:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MNG_ADDR=localhost
      - MNG_PORT=27017
      - MNG_DATABASE=LogsLB
      - MNG_HRMS_Vacation_USER=root
      - MNG_PASSWORD=example
    depends_on:
      - db
      - redis
      - mongo

    
    
  web:
    image: ${DOCKER_REGISTRY-}ecommerceweb
    container_name: ecommerceweb
    build:
      context: .
      dockerfile: E-Commerce.WEB/Dockerfile
    ports:
      - "8068:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - keycloak
    
   
  
