version: "3.9"
services:
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - web

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181


  broker:
    container_name: broker
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'  
  
  redis:
    image: redis:alpine
    platform: linux/arm64
    container_name: redis
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    platform: linux/arm64
    container_name: keycloak
    depends_on:
      - db
    ports:
      - "8080:8080"
    
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres:5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
    command: "-Dkeycloak.profile.feature.upload_scripts=enabled"
    
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak,e-commerce
    volumes:
      - ./db-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

        
        
  api:
    image: ${DOCKER_REGISTRY-}ecommerceapi
    container_name: ecommerceapi
    build:
      context: .
      dockerfile: E-Commerce.API/Dockerfile
    ports:
      - "8023:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MNG_ADDR=localhost
      - MNG_PORT=27017
      - MNG_DATABASE=LogsLB
      - MNG_HRMS_Vacation_USER=root
      - MNG_PASSWORD=example
    depends_on:
      - db
      - redis
      - mongo

    
    
  web:
    image: ${DOCKER_REGISTRY-}ecommerceweb
    container_name: ecommerceweb
    build:
      context: .
      dockerfile: E-Commerce.WEB/Dockerfile
    ports:
      - "8068:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - keycloak
    
   
  ordering:
    image: ${DOCKER_REGISTRY-}ecommerceordering
    container_name: ecommerceordering
    build:
      context: .
      dockerfile: E-Commerce.Ordering/Dockerfile
    ports:
      - "8069:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - broker
    
  payment:
    image: ${DOCKER_REGISTRY-}ecommercepayment
    container_name: ecommercepayment
    build:
      context: .
      dockerfile: E-Commerce.Payment/Dockerfile
    ports:
      - "8070:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - ordering
      - broker
